use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};
use std::{
    collections::{BTreeMap, BTreeSet, HashSet},
    env, fs,
    io::{self, ErrorKind},
    path::{Path, PathBuf},
    process::Command,
};

const PINNED_COMMIT: &str = "2af9e89ba536fad01aa828b06e0ac2174bad0f6d";
const EXERCISE_COUNT: usize = 94;

#[derive(Deserialize)]
struct InfoFile {
    exercises: Vec<InfoExercise>,
}

#[derive(Deserialize)]
struct InfoExercise {
    name: String,
    dir: Option<String>,
    hint: String,
    #[serde(default = "default_true")]
    test: bool,
    #[serde(default)]
    strict_clippy: bool,
    #[serde(default)]
    skip_check_unsolved: bool,
}

const fn default_true() -> bool {
    true
}

#[derive(Serialize)]
struct Manifest {
    schema_version: u8,
    rustlings_version: &'static str,
    upstream: Upstream,
    files: Vec<FileRecord>,
    exercises: Vec<ManifestExercise>,
    cargo: CargoInfrastructure,
}

#[derive(Serialize)]
struct Upstream {
    repository: &'static str,
    tag: &'static str,
    commit: &'static str,
    metadata_path: &'static str,
    license: &'static str,
}

#[derive(Serialize)]
struct FileRecord {
    path: String,
    sha256: String,
}

#[derive(Serialize)]
struct ManifestExercise {
    id: String,
    source: String,
    readme: String,
    solution: String,
    hint: String,
    hint_sha256: String,
    test: bool,
    strict_clippy: bool,
    skip_check_unsolved: bool,
}

#[derive(Serialize)]
struct CargoInfrastructure {
    manifest: &'static str,
    lockfile: &'static str,
}

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let mut args = env::args_os().skip(1);
    let source = args.next().map(PathBuf::from).ok_or_else(|| {
        invalid("usage: import_rustlings <upstream-checkout> [destination] [--check]")
    })?;
    let mut destination = Path::new(env!("CARGO_MANIFEST_DIR")).join("resources/rustlings-6.5.0");
    let mut destination_supplied = false;
    let mut check = false;
    for argument in args {
        if argument == "--check" {
            check = true;
        } else if destination_supplied {
            return Err(invalid("only one destination may be supplied").into());
        } else {
            destination = PathBuf::from(argument);
            destination_supplied = true;
        }
    }

    run(&source, &destination, check).map_err(Into::into)
}

fn run(source: &Path, destination: &Path, check: bool) -> io::Result<()> {
    verify_commit(source)?;
    let parent = destination
        .parent()
        .ok_or_else(|| invalid("destination must have a parent directory"))?;
    fs::create_dir_all(parent)?;
    let generated = parent.join(format!(".rustlings-6.5.0-import-{}", std::process::id()));
    if generated.exists() {
        fs::remove_dir_all(&generated)?;
    }

    let result = (|| {
        generate(source, &generated)?;
        if check {
            if compare_trees(&generated, destination)? {
                println!("bundled Rustlings resources are up to date");
                Ok(())
            } else {
                Err(invalid(
                    "bundled Rustlings resources differ from generated bytes",
                ))
            }
        } else {
            install(&generated, destination)?;
            println!("generated {}", destination.display());
            Ok(())
        }
    })();
    if generated.exists() {
        fs::remove_dir_all(&generated)?;
    }
    result
}

fn verify_commit(source: &Path) -> io::Result<()> {
    let head = Command::new("git")
        .arg("-C")
        .arg(source)
        .args(["rev-parse", "HEAD"])
        .output()?;
    if !head.status.success() || String::from_utf8_lossy(&head.stdout).trim() != PINNED_COMMIT {
        return Err(invalid(format!(
            "source checkout must be at pinned commit {PINNED_COMMIT}"
        )));
    }
    let status = Command::new("git")
        .arg("-C")
        .arg(source)
        .args(["status", "--porcelain", "--untracked-files=all"])
        .output()?;
    if !status.status.success() || !status.stdout.is_empty() {
        return Err(invalid("source checkout must be clean"));
    }
    Ok(())
}

fn generate(source: &Path, destination: &Path) -> io::Result<()> {
    let metadata_path = source.join("rustlings-macros/info.toml");
    let metadata_bytes = read_regular(&metadata_path)?;
    let info: InfoFile = toml::from_str(
        std::str::from_utf8(&metadata_bytes).map_err(|error| invalid(error.to_string()))?,
    )
    .map_err(|error| invalid(format!("invalid upstream metadata: {error}")))?;
    if info.exercises.len() != EXERCISE_COUNT {
        return Err(invalid(format!(
            "expected {EXERCISE_COUNT} exercises, found {}",
            info.exercises.len()
        )));
    }

    fs::create_dir(destination)?;
    copy_regular(&source.join("LICENSE"), &destination.join("LICENSE"))?;
    write_file(&destination.join("info.toml"), &metadata_bytes)?;
    copy_regular(
        &source.join("exercises/README.md"),
        &destination.join("exercises/README.md"),
    )?;
    copy_regular(
        &source.join("solutions/README.md"),
        &destination.join("solutions/README.md"),
    )?;

    let mut ids = HashSet::with_capacity(EXERCISE_COUNT);
    let mut solutions = HashSet::with_capacity(EXERCISE_COUNT);
    let mut readme_dirs = BTreeSet::new();
    let mut exercises = Vec::with_capacity(EXERCISE_COUNT);
    for exercise in info.exercises {
        let dir = exercise
            .dir
            .ok_or_else(|| invalid(format!("exercise {} has no directory", exercise.name)))?;
        if !valid_component(&exercise.name)
            || !valid_component(&dir)
            || !ids.insert(exercise.name.clone())
        {
            return Err(invalid(format!(
                "invalid or duplicate exercise: {}",
                exercise.name
            )));
        }
        let source_path = format!("exercises/{dir}/{}.rs", exercise.name);
        let readme_path = format!("exercises/{dir}/README.md");
        let solution_path = format!("solutions/{dir}/{}.rs", exercise.name);
        if !solutions.insert(solution_path.clone()) {
            return Err(invalid(format!(
                "duplicate solution mapping: {solution_path}"
            )));
        }
        copy_regular(&source.join(&source_path), &destination.join(&source_path))?;
        copy_regular(
            &source.join(&solution_path),
            &destination.join(&solution_path),
        )?;
        if readme_dirs.insert(dir) {
            copy_regular(&source.join(&readme_path), &destination.join(&readme_path))?;
        }
        exercises.push(ManifestExercise {
            id: exercise.name,
            source: source_path,
            readme: readme_path,
            solution: solution_path,
            hint_sha256: digest(exercise.hint.as_bytes()),
            hint: exercise.hint,
            test: exercise.test,
            strict_clippy: exercise.strict_clippy,
            skip_check_unsolved: exercise.skip_check_unsolved,
        });
    }

    write_file(
        &destination.join("Cargo.toml"),
        cargo_manifest(&exercises).as_bytes(),
    )?;
    write_file(&destination.join("Cargo.lock"), cargo_lockfile().as_bytes())?;

    let files = collect_tree(destination)?
        .into_iter()
        .map(|(path, bytes)| FileRecord {
            path,
            sha256: digest(&bytes),
        })
        .collect();
    let manifest = Manifest {
        schema_version: 1,
        rustlings_version: "6.5.0",
        upstream: Upstream {
            repository: "https://github.com/rust-lang/rustlings",
            tag: "v6.5.0",
            commit: PINNED_COMMIT,
            metadata_path: "rustlings-macros/info.toml",
            license: "MIT",
        },
        files,
        exercises,
        cargo: CargoInfrastructure {
            manifest: "Cargo.toml",
            lockfile: "Cargo.lock",
        },
    };
    let mut bytes = serde_json::to_vec_pretty(&manifest)
        .map_err(|error| invalid(format!("manifest serialization failed: {error}")))?;
    bytes.push(b'\n');
    write_file(&destination.join("manifest.json"), &bytes)
}

fn cargo_manifest(exercises: &[ManifestExercise]) -> String {
    let mut output = String::from("bin = [\n");
    for exercise in exercises {
        output.push_str(&format!(
            "  {{ name = \"{}\", path = \"{}\" }},\n",
            exercise.id, exercise.source
        ));
    }
    output.push_str(
        "]\n\n[package]\nname = \"exercises\"\nedition = \"2024\"\n# Don't publish the exercises on crates.io!\npublish = false\n\n[profile.release]\npanic = \"abort\"\n\n[profile.dev]\npanic = \"abort\"\n\n[lints.rust]\n# You shouldn't write unsafe code in Rustlings!\nunsafe_code = \"forbid\"\n# You don't need unstable features in Rustlings and shouldn't rely on them while learning Rust.\nunstable_features = \"forbid\"\n# Dead code warnings can't be avoided in some exercises and might distract while learning.\ndead_code = \"allow\"\n\n[lints.clippy]\n# You forgot a `todo!()`!\ntodo = \"forbid\"\n# This can only happen by mistake in Rustlings.\nempty_loop = \"forbid\"\n# No infinite loops are needed in Rustlings.\ninfinite_loop = \"deny\"\n# You shouldn't leak memory while still learning Rust!\nmem_forget = \"deny\"\n# Currently, there are no disallowed methods. This line avoids problems when developing Rustlings.\ndisallowed_methods = \"allow\"\n",
    );
    output
}

fn cargo_lockfile() -> &'static str {
    "# This file is automatically @generated by Cargo.\n# It is not intended for manual editing.\nversion = 4\n\n[[package]]\nname = \"exercises\"\nversion = \"0.0.0\"\n"
}

fn install(generated: &Path, destination: &Path) -> io::Result<()> {
    if !destination.exists() {
        return fs::rename(generated, destination);
    }
    let backup = destination.with_extension(format!("backup-{}", std::process::id()));
    if backup.exists() {
        fs::remove_dir_all(&backup)?;
    }
    fs::rename(destination, &backup)?;
    if let Err(error) = fs::rename(generated, destination) {
        let _ = fs::rename(&backup, destination);
        return Err(error);
    }
    fs::remove_dir_all(backup)
}

fn compare_trees(left: &Path, right: &Path) -> io::Result<bool> {
    if !right.is_dir() {
        return Ok(false);
    }
    Ok(collect_tree(left)? == collect_tree(right)?)
}

fn collect_tree(root: &Path) -> io::Result<BTreeMap<String, Vec<u8>>> {
    fn visit(
        root: &Path,
        directory: &Path,
        files: &mut BTreeMap<String, Vec<u8>>,
    ) -> io::Result<()> {
        for entry in fs::read_dir(directory)? {
            let entry = entry?;
            let path = entry.path();
            let metadata = fs::symlink_metadata(&path)?;
            if metadata.file_type().is_symlink() {
                return Err(invalid(format!(
                    "symlink is not allowed: {}",
                    path.display()
                )));
            }
            if metadata.is_dir() {
                visit(root, &path, files)?;
            } else if metadata.is_file() {
                let relative = path
                    .strip_prefix(root)
                    .map_err(|error| invalid(error.to_string()))?
                    .to_str()
                    .ok_or_else(|| invalid("non-UTF-8 resource path"))?
                    .replace(std::path::MAIN_SEPARATOR, "/");
                files.insert(relative, fs::read(path)?);
            } else {
                return Err(invalid(format!("non-regular resource: {}", path.display())));
            }
        }
        Ok(())
    }

    let mut files = BTreeMap::new();
    visit(root, root, &mut files)?;
    Ok(files)
}

fn copy_regular(source: &Path, destination: &Path) -> io::Result<()> {
    let bytes = read_regular(source)?;
    write_file(destination, &bytes)
}

fn read_regular(path: &Path) -> io::Result<Vec<u8>> {
    let metadata = fs::symlink_metadata(path)?;
    if metadata.file_type().is_symlink() || !metadata.is_file() {
        return Err(invalid(format!("not a regular file: {}", path.display())));
    }
    fs::read(path)
}

fn write_file(path: &Path, bytes: &[u8]) -> io::Result<()> {
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)?;
    }
    fs::write(path, bytes)
}

fn valid_component(value: &str) -> bool {
    !value.is_empty() && !value.contains(['/', '\\', ':']) && value != "." && value != ".."
}

fn digest(bytes: &[u8]) -> String {
    format!("{:x}", Sha256::digest(bytes))
}

fn invalid(message: impl Into<String>) -> io::Error {
    io::Error::new(ErrorKind::InvalidData, message.into())
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::sync::atomic::{AtomicU64, Ordering};

    struct TempDir(PathBuf);

    impl TempDir {
        fn new() -> Self {
            static NEXT_ID: AtomicU64 = AtomicU64::new(0);
            let path = env::temp_dir().join(format!(
                "rustlings-import-test-{}-{}",
                std::process::id(),
                NEXT_ID.fetch_add(1, Ordering::Relaxed)
            ));
            fs::create_dir(&path).unwrap();
            Self(path)
        }
    }

    impl Drop for TempDir {
        fn drop(&mut self) {
            let _ = fs::remove_dir_all(&self.0);
        }
    }

    #[test]
    fn wrong_commit_is_rejected_before_destination_mutation() {
        let temp = TempDir::new();
        let source = temp.0.join("source");
        let destination = temp.0.join("destination");
        fs::create_dir(&source).unwrap();
        fs::create_dir(&destination).unwrap();
        fs::write(source.join("file"), "source").unwrap();
        fs::write(destination.join("sentinel"), "unchanged").unwrap();

        assert!(Command::new("git")
            .arg("init")
            .arg(&source)
            .status()
            .unwrap()
            .success());
        assert!(Command::new("git")
            .arg("-C")
            .arg(&source)
            .args(["add", "file"])
            .status()
            .unwrap()
            .success());
        assert!(Command::new("git")
            .arg("-C")
            .arg(&source)
            .args([
                "-c",
                "user.name=Rustlings Import Test",
                "-c",
                "user.email=test@example.invalid",
                "commit",
                "-m",
                "fixture",
            ])
            .status()
            .unwrap()
            .success());

        assert!(run(&source, &destination, false).is_err());
        assert_eq!(
            fs::read_to_string(destination.join("sentinel")).unwrap(),
            "unchanged"
        );
        assert_eq!(fs::read_dir(&destination).unwrap().count(), 1);
    }
}
